# Auto-generated by gen_sources.py. Do not edit.

ZM_DEFS := -DZMUSIC_STATIC -DMINIZ_NO_STDIO -DADLMIDI_DISABLE_MIDI_SEQUENCER -DADLMIDI_ENABLE_OPL2_LLE_EMULATOR -DADLMIDI_ENABLE_OPL3_LLE_EMULATOR -DOPNMIDI_DISABLE_MIDI_SEQUENCER -DOPNMIDI_ENABLE_OPN2_LLE_EMULATOR -DHAVE_POWF=1 -DLIBXMP_STATIC=1 -DLIBXMP_NO_PROWIZARD=1 -DLIBXMP_NO_DEPACKERS=1 -DVGM_YM2612_NUKED -D__EMSCRIPTEN__ -DNEED_ITOA -DHAVE_SNDFILE -I$(ROOT)/libraries/libsnd/include -DHAVE_MPG123 -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp
ZM_GLOBAL_INC := -I$(ROOT)/libraries/mpg123/src/include -I$(ROOT)/libraries/ZMusic/../libsnd/include -I$(ROOT)/libraries/ZMusic/include -I$(ROOT)/libraries/ZMusic/source -I$(ROOT)/libraries/ZMusic/source/zmusic -I$(ROOT)/libraries/ZMusic/source/decoder -I$(ROOT)/libraries/ZMusic/thirdparty/adlmidi -I$(ROOT)/libraries/ZMusic/thirdparty/opnmidi -I$(ROOT)/libraries/ZMusic/thirdparty/dumb/include -I$(ROOT)/libraries/ZMusic/thirdparty/timidity -I$(ROOT)/libraries/ZMusic/thirdparty/timidity/timidity -I$(ROOT)/libraries/ZMusic/thirdparty/timidityplus -I$(ROOT)/libraries/ZMusic/thirdparty/timidityplus/timiditypp -I$(ROOT)/libraries/ZMusic/thirdparty/wildmidi -I$(ROOT)/libraries/ZMusic/thirdparty/wildmidi/wildmidi -I$(ROOT)/libraries/ZMusic/thirdparty/oplsynth -I$(ROOT)/libraries/ZMusic/thirdparty/oplsynth/oplsynth -I$(ROOT)/libraries/ZMusic/thirdparty/libxmp/include -I$(ROOT)/libraries/ZMusic/thirdparty/libxmp/src -I$(ROOT)/libraries/ZMusic/thirdparty/miniz -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu/gme -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu/gme/ext -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/drivers -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/synth -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/rvoice -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/midi -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/utils -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/sfloader -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/bindings -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/include -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth

ZM_GROUPS := core libxmp dumb gme fluidsynth adlmidi opnmidi timidityplus timidity oplsynth wildmidi

ZM_core_SRCS := \
	libraries/ZMusic/source/decoder/mpg123_decoder.cpp \
	libraries/ZMusic/source/decoder/sndfile_decoder.cpp \
	libraries/ZMusic/source/decoder/sounddecoder.cpp \
	libraries/ZMusic/source/loader/i_module.cpp \
	libraries/ZMusic/source/loader/test.c \
	libraries/ZMusic/source/mididevices/music_adlmidi_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_base_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_fluidsynth_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_opl_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_opnmidi_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_softsynth_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_timidity_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_timiditypp_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_wavewriter_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_wildmidi_mididevice.cpp \
	libraries/ZMusic/source/mididevices/music_win_mididevice.cpp \
	libraries/ZMusic/source/midisources/midisource.cpp \
	libraries/ZMusic/source/midisources/midisource_hmi.cpp \
	libraries/ZMusic/source/midisources/midisource_mids.cpp \
	libraries/ZMusic/source/midisources/midisource_mus.cpp \
	libraries/ZMusic/source/midisources/midisource_smf.cpp \
	libraries/ZMusic/source/midisources/midisource_xmi.cpp \
	libraries/ZMusic/source/musicformats/music_cd.cpp \
	libraries/ZMusic/source/musicformats/music_midi.cpp \
	libraries/ZMusic/source/musicformats/music_stream.cpp \
	libraries/ZMusic/source/streamsources/music_dumb.cpp \
	libraries/ZMusic/source/streamsources/music_gme.cpp \
	libraries/ZMusic/source/streamsources/music_libsndfile.cpp \
	libraries/ZMusic/source/streamsources/music_libxmp.cpp \
	libraries/ZMusic/source/streamsources/music_opl.cpp \
	libraries/ZMusic/source/streamsources/music_xa.cpp \
	libraries/ZMusic/source/zmusic/configuration.cpp \
	libraries/ZMusic/source/zmusic/critsec.cpp \
	libraries/ZMusic/source/zmusic/zmusic.cpp \

ZM_core_INC := -I$(ROOT)/libraries/ZMusic/include -I$(ROOT)/libraries/ZMusic/source -I$(ROOT)/libraries/ZMusic/source/zmusic -I$(ROOT)/libraries/ZMusic/source/decoder

ZM_libxmp_SRCS := \
	libraries/ZMusic/thirdparty/libxmp/src/control.c \
	libraries/ZMusic/thirdparty/libxmp/src/dataio.c \
	libraries/ZMusic/thirdparty/libxmp/src/effects.c \
	libraries/ZMusic/thirdparty/libxmp/src/extras.c \
	libraries/ZMusic/thirdparty/libxmp/src/far_extras.c \
	libraries/ZMusic/thirdparty/libxmp/src/filetype.c \
	libraries/ZMusic/thirdparty/libxmp/src/filter.c \
	libraries/ZMusic/thirdparty/libxmp/src/flow.c \
	libraries/ZMusic/thirdparty/libxmp/src/format.c \
	libraries/ZMusic/thirdparty/libxmp/src/hio.c \
	libraries/ZMusic/thirdparty/libxmp/src/hmn_extras.c \
	libraries/ZMusic/thirdparty/libxmp/src/lfo.c \
	libraries/ZMusic/thirdparty/libxmp/src/load.c \
	libraries/ZMusic/thirdparty/libxmp/src/load_helpers.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/669_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/abk_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/amf_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/arch_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/asylum_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/chip_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/coco_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/common.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/dbm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/digi_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/dt_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/emod_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/far_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/flt_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/fnk_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/gal4_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/gal5_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/gdm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/hmn_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/ice_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/iff.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/imf_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/ims_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/it_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/itsex.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/liq_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/lzw.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/masi16_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/masi_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mdl_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/med2_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/med3_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/med4_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mfp_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mgt_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mmd1_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mmd3_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mmd_common.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mod_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/mtm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/muse_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/no_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/okt_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/pt3_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/ptm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/pw_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/rtm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/s3m_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/sample.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/sfx_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/st_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/stim_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/stm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/stx_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/sym_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/ult_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/umx_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/voltable.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/vorbis.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/xm_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/loaders/xmf_load.c \
	libraries/ZMusic/thirdparty/libxmp/src/md5.c \
	libraries/ZMusic/thirdparty/libxmp/src/med_extras.c \
	libraries/ZMusic/thirdparty/libxmp/src/memio.c \
	libraries/ZMusic/thirdparty/libxmp/src/misc.c \
	libraries/ZMusic/thirdparty/libxmp/src/mix_all.c \
	libraries/ZMusic/thirdparty/libxmp/src/mix_paula.c \
	libraries/ZMusic/thirdparty/libxmp/src/mixer.c \
	libraries/ZMusic/thirdparty/libxmp/src/mkstemp.c \
	libraries/ZMusic/thirdparty/libxmp/src/period.c \
	libraries/ZMusic/thirdparty/libxmp/src/player.c \
	libraries/ZMusic/thirdparty/libxmp/src/read_event.c \
	libraries/ZMusic/thirdparty/libxmp/src/rng.c \
	libraries/ZMusic/thirdparty/libxmp/src/scan.c \
	libraries/ZMusic/thirdparty/libxmp/src/smix.c \
	libraries/ZMusic/thirdparty/libxmp/src/tempfile.c \
	libraries/ZMusic/thirdparty/libxmp/src/virtual.c \
	libraries/ZMusic/thirdparty/libxmp/src/win32.c \

ZM_libxmp_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/libxmp/include -I$(ROOT)/libraries/ZMusic/thirdparty/libxmp/src -I$(ROOT)/libraries/ZMusic/thirdparty/miniz

ZM_dumb_SRCS := \
	libraries/ZMusic/thirdparty/dumb/src/core/atexit.c \
	libraries/ZMusic/thirdparty/dumb/src/core/duhlen.c \
	libraries/ZMusic/thirdparty/dumb/src/core/duhtag.c \
	libraries/ZMusic/thirdparty/dumb/src/core/dumbfile.c \
	libraries/ZMusic/thirdparty/dumb/src/core/loadduh.c \
	libraries/ZMusic/thirdparty/dumb/src/core/makeduh.c \
	libraries/ZMusic/thirdparty/dumb/src/core/rawsig.c \
	libraries/ZMusic/thirdparty/dumb/src/core/readduh.c \
	libraries/ZMusic/thirdparty/dumb/src/core/register.c \
	libraries/ZMusic/thirdparty/dumb/src/core/rendduh.c \
	libraries/ZMusic/thirdparty/dumb/src/core/rendsig.c \
	libraries/ZMusic/thirdparty/dumb/src/core/unload.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/barray.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/clickrem.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/lpc.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/memfile.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/resample.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/resampler.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/riff.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/sampbuf.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/silence.c \
	libraries/ZMusic/thirdparty/dumb/src/helpers/stdfile.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itload.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itload2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itmisc.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itorder.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itread.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itread2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itrender.c \
	libraries/ZMusic/thirdparty/dumb/src/it/itunload.c \
	libraries/ZMusic/thirdparty/dumb/src/it/load669.c \
	libraries/ZMusic/thirdparty/dumb/src/it/load6692.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadamf.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadamf2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadany.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadany2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadasy.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadasy2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadmod.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadmod2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadmtm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadmtm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadokt.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadokt2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadoldpsm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadoldpsm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadpsm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadpsm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadptm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadptm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadriff.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadriff2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loads3m.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loads3m2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadstm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadstm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadxm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/loadxm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/ptmeffect.c \
	libraries/ZMusic/thirdparty/dumb/src/it/read669.c \
	libraries/ZMusic/thirdparty/dumb/src/it/read6692.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readam.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readamf.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readamf2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readany.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readany2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readasy.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readdsmf.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readmod.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readmod2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readmtm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readokt.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readokt2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readoldpsm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readpsm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readptm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readriff.c \
	libraries/ZMusic/thirdparty/dumb/src/it/reads3m.c \
	libraries/ZMusic/thirdparty/dumb/src/it/reads3m2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readstm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readstm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readxm.c \
	libraries/ZMusic/thirdparty/dumb/src/it/readxm2.c \
	libraries/ZMusic/thirdparty/dumb/src/it/xmeffect.c \

ZM_dumb_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/dumb/include

ZM_gme_SRCS := \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Ay_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Ay_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Ay_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Blip_Buffer.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Classic_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Data_Reader.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Dual_Resampler.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Effects_Buffer.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Fir_Resampler.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gb_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gb_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gb_Oscs.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gbs_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gme_File.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Gym_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Hes_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Hes_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Hes_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Kss_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Kss_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Kss_Scc_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/M3u_Playlist.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Multi_Buffer.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Music_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Fds_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Fme7_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Namco_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Oscs.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Vrc6_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nes_Vrc7_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nsf_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Nsfe_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Sap_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Sap_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Sap_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Sms_Apu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Snes_Spc.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Spc_Cpu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Spc_Dsp.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Spc_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Spc_Filter.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Vgm_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Vgm_Emu_Impl.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Ym2413_Emu.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/Ym2612_Nuked.cpp \
	libraries/ZMusic/thirdparty/game-music-emu/gme/ext/emu2413.c \
	libraries/ZMusic/thirdparty/game-music-emu/gme/ext/panning.c \
	libraries/ZMusic/thirdparty/game-music-emu/gme/gme.cpp \

ZM_gme_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu/gme -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu/gme/ext -I$(ROOT)/libraries/ZMusic/thirdparty/game-music-emu -I$(ROOT)/libraries/ZMusic/thirdparty/miniz

ZM_fluidsynth_SRCS := \
	libraries/ZMusic/thirdparty/fluidsynth/src/bindings/fluid_filerenderer.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/bindings/fluid_ladspa.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/drivers/fluid_adriver.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/drivers/fluid_mdriver.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_midi.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_midi_router.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_seq.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_seq_queue.cpp \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_seqbind.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/midi/fluid_seqbind_notes.cpp \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_adsr_env.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_chorus.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_iir_filter.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_iir_filter_impl.cpp \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_lfo.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_rev.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_rvoice.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_rvoice_dsp.cpp \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_rvoice_event.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/rvoice/fluid_rvoice_mixer.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/sfloader/fluid_defsfont.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/sfloader/fluid_samplecache.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/sfloader/fluid_sffile.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/sfloader/fluid_sfont.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_chan.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_event.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_gen.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_mod.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_synth.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_synth_monopoly.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_tuning.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/synth/fluid_voice.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_conv.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_hash.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_list.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_ringbuffer.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_settings.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/fluid_sys.c \
	libraries/ZMusic/thirdparty/fluidsynth/src/utils/win32_glibstubs.c \

ZM_fluidsynth_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/drivers -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/synth -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/rvoice -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/midi -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/utils -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/sfloader -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/src/bindings -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth/include -I$(ROOT)/libraries/ZMusic/thirdparty/fluidsynth -I$(ROOT)/libraries/ZMusic/source/decoder

ZM_adlmidi_SRCS := \
	libraries/ZMusic/thirdparty/adlmidi/adlmidi.cpp \
	libraries/ZMusic/thirdparty/adlmidi/adlmidi_load.cpp \
	libraries/ZMusic/thirdparty/adlmidi/adlmidi_midiplay.cpp \
	libraries/ZMusic/thirdparty/adlmidi/adlmidi_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/adlmidi_private.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/dosbox/dbopl.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/dosbox_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/esfmu/esfm.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/esfmu/esfm_registers.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/esfmu_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/java_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/mame_opl2.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/nuked/nukedopl3.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/nuked/nukedopl3_174.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/nuked_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/nuked_opl3_v174.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/opal/opal.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/opal_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ym3812_lle.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ym3812_lle/nopl2.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/ym3812_lle/nuked_fmopl2.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymf262_lle.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymf262_lle/nopl3.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymf262_lle/nuked_fmopl3.c \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm/ymfm_adpcm.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm/ymfm_misc.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm/ymfm_opl.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm/ymfm_pcm.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm/ymfm_ssg.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm_opl2.cpp \
	libraries/ZMusic/thirdparty/adlmidi/chips/ymfm_opl3.cpp \
	libraries/ZMusic/thirdparty/adlmidi/inst_db.cpp \
	libraries/ZMusic/thirdparty/adlmidi/wopl/wopl_file.c \

ZM_adlmidi_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/adlmidi

ZM_opnmidi_SRCS := \
	libraries/ZMusic/thirdparty/opnmidi/chips/gens/Ym2612.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/gens_opn2.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/mame/mame_ym2612fm.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/mame_opn2.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/mame_opna.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/mamefm/emu2149.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/mamefm/fm.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/mamefm/resampler.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/mamefm/ymdeltat.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2/fmgen_file.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2/fmgen_fmgen.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2/fmgen_fmtimer.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2/fmgen_opna.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2/fmgen_psg.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/np2_opna.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked/ym3438.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked_lle/fmopn2.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked_lle/fmopna_2612.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked_lle/nopn2.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked_lle/nopn2f.c \
	libraries/ZMusic/thirdparty/opnmidi/chips/nuked_opn2.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/ym2612_lle.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/ymf276_lle.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/ymfm/ymfm_opn.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/ymfm_opn2.cpp \
	libraries/ZMusic/thirdparty/opnmidi/chips/ymfm_opna.cpp \
	libraries/ZMusic/thirdparty/opnmidi/opnmidi.cpp \
	libraries/ZMusic/thirdparty/opnmidi/opnmidi_load.cpp \
	libraries/ZMusic/thirdparty/opnmidi/opnmidi_midiplay.cpp \
	libraries/ZMusic/thirdparty/opnmidi/opnmidi_opn2.cpp \
	libraries/ZMusic/thirdparty/opnmidi/opnmidi_private.cpp \
	libraries/ZMusic/thirdparty/opnmidi/wopn/wopn_file.c \

ZM_opnmidi_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/opnmidi

ZM_timidityplus_SRCS := \
	libraries/ZMusic/thirdparty/timidityplus/common.cpp \
	libraries/ZMusic/thirdparty/timidityplus/configfile.cpp \
	libraries/ZMusic/thirdparty/timidityplus/effect.cpp \
	libraries/ZMusic/thirdparty/timidityplus/fft4g.cpp \
	libraries/ZMusic/thirdparty/timidityplus/filter.cpp \
	libraries/ZMusic/thirdparty/timidityplus/freq.cpp \
	libraries/ZMusic/thirdparty/timidityplus/instrum.cpp \
	libraries/ZMusic/thirdparty/timidityplus/mblock.cpp \
	libraries/ZMusic/thirdparty/timidityplus/mix.cpp \
	libraries/ZMusic/thirdparty/timidityplus/playmidi.cpp \
	libraries/ZMusic/thirdparty/timidityplus/quantity.cpp \
	libraries/ZMusic/thirdparty/timidityplus/readmidic.cpp \
	libraries/ZMusic/thirdparty/timidityplus/recache.cpp \
	libraries/ZMusic/thirdparty/timidityplus/resample.cpp \
	libraries/ZMusic/thirdparty/timidityplus/reverb.cpp \
	libraries/ZMusic/thirdparty/timidityplus/sbkconv.cpp \
	libraries/ZMusic/thirdparty/timidityplus/sffile.cpp \
	libraries/ZMusic/thirdparty/timidityplus/sfitem.cpp \
	libraries/ZMusic/thirdparty/timidityplus/smplfile.cpp \
	libraries/ZMusic/thirdparty/timidityplus/sndfont.cpp \
	libraries/ZMusic/thirdparty/timidityplus/tables.cpp \

ZM_timidityplus_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/timidityplus/timiditypp -I$(ROOT)/libraries/ZMusic/thirdparty/timidityplus

ZM_timidity_SRCS := \
	libraries/ZMusic/thirdparty/timidity/common.cpp \
	libraries/ZMusic/thirdparty/timidity/instrum.cpp \
	libraries/ZMusic/thirdparty/timidity/instrum_dls.cpp \
	libraries/ZMusic/thirdparty/timidity/instrum_font.cpp \
	libraries/ZMusic/thirdparty/timidity/instrum_sf2.cpp \
	libraries/ZMusic/thirdparty/timidity/mix.cpp \
	libraries/ZMusic/thirdparty/timidity/playmidi.cpp \
	libraries/ZMusic/thirdparty/timidity/resample.cpp \
	libraries/ZMusic/thirdparty/timidity/timidity.cpp \

ZM_timidity_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/timidity/timidity -I$(ROOT)/libraries/ZMusic/thirdparty/timidity

ZM_oplsynth_SRCS := \
	libraries/ZMusic/thirdparty/oplsynth/OPL3.cpp \
	libraries/ZMusic/thirdparty/oplsynth/dosbox/opl.cpp \
	libraries/ZMusic/thirdparty/oplsynth/fmopl.cpp \
	libraries/ZMusic/thirdparty/oplsynth/musicblock.cpp \
	libraries/ZMusic/thirdparty/oplsynth/nukedopl3.cpp \
	libraries/ZMusic/thirdparty/oplsynth/opl_mus_player.cpp \
	libraries/ZMusic/thirdparty/oplsynth/oplio.cpp \

ZM_oplsynth_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/oplsynth/oplsynth -I$(ROOT)/libraries/ZMusic/thirdparty/oplsynth

ZM_wildmidi_SRCS := \
	libraries/ZMusic/thirdparty/wildmidi/file_io.cpp \
	libraries/ZMusic/thirdparty/wildmidi/gus_pat.cpp \
	libraries/ZMusic/thirdparty/wildmidi/reverb.cpp \
	libraries/ZMusic/thirdparty/wildmidi/wildmidi_lib.cpp \
	libraries/ZMusic/thirdparty/wildmidi/wm_error.cpp \

ZM_wildmidi_INC := -I$(ROOT)/libraries/ZMusic/thirdparty/wildmidi/wildmidi -I$(ROOT)/libraries/ZMusic/thirdparty/wildmidi

